name: Convert PDF to Image Daily

on:
  schedule:
    - cron: '0 18 * * *'  # UTC時間で毎日03:00 JST（9時間ずらす）
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y poppler-utils

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Download PDF from Google Drive
      run: |
        curl -L -o Calendar.pdf "https://drive.google.com/uc?export=download&id=1TBZaXPWz85Eh8z5tGYy-NKTuV7nJhqLa"

    - name: Convert PDF to PNG
      run: python pdf_to_image.py

    - name: Upload images to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output_images

    - name: Push to gh-pages
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push origin gh-pages
    
